# Site settings
title: sandbox.es
email: jeslopalo_at_sandbox_dot_es
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sandbox.es" # the base hostname & protocol for your site
twitter_username: jeslopalo
github_username:  jeslopalo

# Build settings
markdown: kramdown
