# Site settings
title: sandbox.es
email: jesus@sandbox.es
description: > # this means to ignore newlines until "baseurl:"
 This is my personal site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sandbox.es" # the base hostname & protocol for your site

author: jeslopalo

timezone: Europe/Madrid

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

services:
  disqus_shortname: sandboxes

# Build settings
permalink: "/posts/:year/:month/:day/:title/"
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - node_modules

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#
sass:
    style: compressed
    sass_dir: assets/_sass



# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  ignore:
    envs: [development, local]

#       _______  _______  _______  _______ _________ _______
#      (  ___  )(  ____ \(  ____ \(  ____ \\__   __/(  ____ \
#      | (   ) || (    \/| (    \/| (    \/   ) (   | (    \/
#      | (___) || (_____ | (_____ | (__       | |   | (_____
#      |  ___  |(_____  )(_____  )|  __)      | |   (_____  )
#      | (   ) |      ) |      ) || (         | |         ) |
#      | )   ( |/\____) |/\____) || (____/\   | |   /\____) |
#      |/     \|\_______)\_______)(_______/   )_(   \_______)
#
assets:
  images:
    masthead:
      default: /assets/images/header/default/lego-header.jpg

#                  ____          __  _
#      _________  / / /__  _____/ /_(_)___  ____  _____
#     / ___/ __ \/ / / _ \/ ___/ __/ / __ \/ __ \/ ___/
#    / /__/ /_/ / / /  __/ /__/ /_/ / /_/ / / / (__  )
#    \___/\____/_/_/\___/\___/\__/_/\____/_/ /_/____/
#
collections:
  games:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name


#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: "_games"
      type: "games"
    values:
      language: es
      show_meta: false
      comments: false
      author: jeslopalo
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      language: es
      show_meta: false
      comments: false
      author: jeslopalo
  -
    scope:
      path: "pages" 		# an empty string here means all files in the project
      type: "pages"
    values:
      language: es
      show_meta: false 	    # Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      language: es
      show_meta: true       # Show metadata for all posts
      # permalink: "/posts/:year/:month/:day/:title/" # not supported by github pages
      # sidebar:            # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: jeslopalo     # Default author for posts
  -
    scope:
      path: "assets"
    values:
      sitemap:
        exclude: true
  -
    scope:
      path: "assets/images/header"
    values:
      masthead_image: true
  -
    scope:
      path: "assets/images"
    values:
      image: true

#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/footer_scripts

google_analytics_tracking_id: UA-67501983-1



#                       __       _                  __
#       ____ ___  ___  / /______(_)________  ____  / /
#      / __ `__ \/ _ \/ __/ ___/ / ___/ __ \/ __ \/ /
#     / / / / / /  __/ /_/ /  / / /__/ /_/ / /_/ / /
#    /_/ /_/ /_/\___/\__/_/  /_/\___/\____/\____/_/
#
# https://metricool.com

metricool_tracking_id: 7efe9e82a9f4b5c0aecdbf1463703f52
