# Site settings
title: sandbox.es
email: jesus@sandbox.es
description: > # this means to ignore newlines until "baseurl:"
 This is my personal site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sandbox.es" # the base hostname & protocol for your site

author: jeslopalo

services:
  disqus_shortname: sandboxes

# Build settings
permalink: /:categories/:title/
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - node_modules

markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#
sass:
    style: compressed
    sass_dir: assets/_sass



# Used › default.html front-matter and comress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  ignore:
    envs: [development, local]


#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false 	    # Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: jeslopalo     # Default author for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true       # Show metadata for all posts
      # sidebar:            # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: jeslopalo     # Default author for posts
